### ISSUE TITLE
Issue: sitemap

### ISSUE THREAD

**Issue by necrux** [piazzai/cvless#1]
Loving the theme! Any thoughts on why I am getting a 404 on `/sitemap.xml` though? It is loading properly under `_site` when I build locally, but it is not loading on GitHub Pages.

I know this is not really in your purview but I thought you may have ran into it as well. Thanks!

**Comment by necrux** [comment]
Looks like it was resolved by adding the following to `_config.yml`:

```
# Plugins
plugins:
  - jekyll-sitemap
# mimic GitHub Pages with --safe
whitelist:
  - jekyll-sitemap
```

**Comment by piazzai** [comment]
Good catch! I didn't realize this because the demo site is hosted on netlify, which loads the sitemap correctly. I implemented your solution into the template. Thanks.
