### ISSUE TITLE
application error

### ISSUE THREAD

**Issue by habib-Bashi** [piazzai/cvless#4]
I am receiving an application error message after my deployment from my local machine to Azure web services.

I am using ubuntu 18.4 and using vs code Azure extension for deployment. 

Looking forward to your support.

with thanks,
Habib

**Comment by piazzai** [comment]
Hi Habib. Could you provide more details about the error you're getting? It would be helpful to see the error message.

**Comment by habib-Bashi** [comment]
I am getting a 401 deployment fail error message; I have used the Azure web app services deployment management tool.

<img width="601" alt="image" src="https://github.com/piazzai/cvless/assets/65003028/6d47e23e-6439-4087-af34-103e847d05a2">

**Comment by piazzai** [comment]
I am not sure what's causing the error but it seems to be a problem with Azure Web rather than cvless. The theme (as distributed) works on GitHub Pages and Netlify. The only solution I can offer is to use one of those services.

Sorry I could not be of more help.

**Comment by habib-Bashi** [comment]
First, thank you so much for your email.

Good morning,

Yes, you are right, I am facing an error during the deployment to Azure web
services, and the website works fine on GitHub.

Cheer,
Habib
